### ISSUE TITLE
Command-line Hector reading and to-do lists

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#383]
Here's a suggested list. Happy to chat/modify as needed.

## C++

- [x] Don't dive _too_ deep but work through [the basics of C++ syntax](http://www.cplusplus.com/doc/tutorial/)

## Hector code

- [x] Read the Hector manual's [Programming Topics](https://jgcri.github.io/hector/articles/manual/#programming-topics) section

## Building command-line Hector

- [x] Understand Bash [environment variables](https://linuxhint.com/bash-environment-variables/)
- [x] Understand the basics of [makefiles](https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/)
- [x] What environment variables does the Hector makefile use? How is this handled in the Travis testing that calls `make`?

## Xcode

- [x] Look through the various build and scheme options in Xcode; understand how to [manage schemes](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ManagingSchemes.html)
- [x] Read about [debugging in Xcode](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/debugging_tools.html)  **oh I'm going to read this one too**
- [x] Set a breakpoint at the beginning of `getData()`, around line 470, in `simpleNbox.cpp`. Run the model and it will go into the debugger. Walk through the stack trace. What's happening at each level? How can you tell whether the model is in spinup or historical mode?
- [x] Add a condition to your breakpoint such that it will only trigger in historical (not spinup) mode and re-run

## Travis tests

- [x] Look through the [.travis.yml](https://github.com/JGCRI/hector/blob/master/.travis.yml) configuration file. Why do we build and test Hector twice? What else happens?

**Comment by kdorheim** [comment]
> What environment variables does the Hector makefile use? How is this handled in the Travis testing that calls make?

Environment variables in the Hector makefile, well looking in `hector/src/makefile.standalone` it looks like there are number of environment variables related to compiling Hector  and please correct me if I am wrong but it looks like a number of them are wrapped up into `CXXFLAGS` and `OPTFLAGS`. There are also a number of variables related to the version of BOOST being used. Is that what you are asking about? 

And then with travis checking out the .yml file it the same make file is executed but only after the environment variables were defined. I assume that means that they these environment variables supersede the boost related ones defined in the make file?

**Comment by bpbond** [comment]
@kdorheim Yes true, inside the script they're wrapped up in `CXXFLAGS` and `OPTFLAGS` and then exported. But the script takes a couple from outside, in particular (as you note) `BOOSTROOT` and `BOOSTLIBS`. (These same environmental variables are also used in the Xcode settings.) These are the ones I was really thinking of, because they have to be defined first--as we can see in the .`travis.yml`:
```
      before_script:
        - "export BOOSTROOT=/usr/include/x86_64-linux-gnu/"
        - "export BOOSTLIB=/usr/lib/x86_64-linux-gnu/"
```

**Comment by kdorheim** [comment]
So with Xcode these would also have to be set defined elsewhere? It wouldn't work to install and build the boost libs in the `hector/src` directory?

**Comment by bpbond** [comment]
Right, currently they have to be defined in your `.bash_profile` for example.

**Comment by bpbond** [comment]
Thanks @rgieseke ! We really appreciate your sustained interest and contributions.
