### ISSUE TITLE
Tracking upgrades

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#467]
As I finalize #466 , some thoughts:

- [x] We'll want a tracking vignette
- [x] Remove the diff stuff in the tracking code (after checking the need for it has been addressed)
- [x] Ideally the user can use a new function `fetchtracking()` to get the tracking output data from within R
- [x] Right now the tracking output file looks like this; rethink at all?

year | pool_name | pool_value | pool_units | source_name | source_fraction
-- | -- | -- | -- | -- | --
1746 | Diff | -0.6125 | U_PGC | veg_diff | 0
1746 | Diff | 15.7918 | U_PGC | soil_diff | 0

**Comment by dawnlwoodard** [comment]
Not sure I understand the Diff. But from the column names I would expect the first couple rows might look like: c("year"=1746, "pool_name"="soil", "pool_value"=1700, "pool_units"="U_PGC", "source_name"="soil", "source_fraction"=0.4); c("year"=1746, "pool_name"="soil", "pool_value"=1700, "pool_units"="U_PGC", "source_name"="atmosphere", "source_fraction"=0.3). Is that the intention? Or can you explain the example you show here?

**Comment by bpbond** [comment]
Sorry, that was more of a note to myself (in terms of clarity). I was just wondering:
* Are there were any other columns we would want? `component` perhaps?
* Should column names be consistent with (but not identical to) the standard csv output files (below)? Probably

```
year,run_name,spinup,component,variable,value,units
```
