### ISSUE TITLE
Revision checklist

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#730]
Feel free to edit @kdorheim 

## Before distribution to coauthors

- [x] Mostly-finalized response doc
- [x] Ideally, have a draft of new Table 3
- [x] Ideally, try adding other RCMs to Figure 5 (?) - we mentioned this yesterday
- [x] Ideally, fill in line numbers for them in response doc
- [x] Give co-authors response doc and clean document
- [x] Tag Steve in particular about a few aerosol questions

## Before resubmission

- [x] Read back to front
- [x] Reformat citations and check all against reference list
- [x] Check all figures and tables are referenced in the main text
- [x] Check supplementary material referenced in main text
- [x] Create a release for v3.2 and update all references in paper and documentation
- [x] Fill in line numbers in response doc
- [x] Final search for TODOs and XXXs

**Comment by rgieseke** [comment]
> Create a release for v3.2 and update all references in paper and documentation

Has this actually been done? (It's checked, but I don't find a tag or release)

**Comment by kdorheim** [comment]
@rgieseke V3.2.0 should be available now!
